[package]
name = "rust_sls_common"
version = "1.0.0"
authors = ["Eduardo Sabino <eduardo@amo.delivery>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = "1.0.118"
mongodb = { version = "1.1.1", features = ["async-std-runtime"], default-features = false }